from pydantic import BaseModel, EmailStr, field_validator
from typing import Optional
from datetime import datetime
from app.models.user import UserRole


class UpdateProfileRequest(BaseModel):
    full_name: Optional[str] = None
    phone: Optional[str] = None
    city: Optional[str] = None


class ChangePasswordRequest(BaseModel):
    current_password: str
    new_password: str

    @field_validator("new_password")
    @classmethod
    def password_strength(cls, v: str) -> str:
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters")
        return v


class ChangeEmailRequest(BaseModel):
    new_email: EmailStr
    password: str  # re-verify identity


class SignupRequest(BaseModel):
    full_name: str
    email: EmailStr
    password: str
    phone: Optional[str] = None
    role: UserRole = UserRole.public
    # Role-conditional fields
    organization: Optional[str] = None
    license_number: Optional[str] = None
    designation: Optional[str] = None
    city: Optional[str] = None

    @field_validator("password")
    @classmethod
    def password_strength(cls, v: str) -> str:
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters")
        return v

    @field_validator("license_number")
    @classmethod
    def license_required_for_roles(cls, v, info):
        role = info.data.get("role")
        if role in (UserRole.pharmacist, UserRole.investigator) and not v:
            raise ValueError("License number is required for pharmacist/investigator roles")
        return v


class LoginRequest(BaseModel):
    email: EmailStr
    password: str
    device_id: str  # unique identifier for the device (e.g. UUID generated by the client)


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"


class RefreshTokenRequest(BaseModel):
    refresh_token: str


class UserResponse(BaseModel):
    id: int
    full_name: str
    email: str
    phone: Optional[str] = None
    role: UserRole
    organization: Optional[str] = None
    license_number: Optional[str] = None
    designation: Optional[str] = None
    city: Optional[str] = None
    is_active: Optional[int] = None
    created_at: Optional[datetime] = None
    profile_photo: Optional[str] = None

    model_config = {"from_attributes": True}
